print(5/0)

# The error reported back 'zeridivisionerror: division by zero', is an 
# exception object. Python creates this kind of object in response to a 
# situation where it can't do what we ask it

